config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, skip: [:registrations]
  root to: 'pages#home'
  resources :blogposts, only: %i[show index]
  get 'mentions-legales', to: 'pages#legals'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  belongs_to :user
  validates :title, :content, :photo, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogposts, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def authenticate_admin!
    redirect_to new_user_session_path unless current_user.admin
  end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @blogposts = Blogpost.order('created_at DESC')
  end

  def show
    @blogpost = Blogpost.find(params[:id])
  end

  private

  def blogpost_params
    params.require(:blogpost).permit(:title, :content, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :legals]

  def home
    @blogposts = Blogpost.order('created_at DESC').first(3)
  end

  def legals
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_keywords
    content_for?(:meta_keywords) ? content_for(:meta_keywords) : DEFAULT_META["meta_keywords"]
  end

  def meta_image
    image = content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"]
    # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
    # avec une image dans vos assets ou une url absolue
    image.starts_with?("http") ? image : image_url(image)
  end
end

app/views/blogposts/index.html.erb
<% content_for :meta_title, "Chez Valou - Actualités" %>
<% content_for :meta_description, "Découvrez les dernières actualités de Chez Valou Pâtisserie - Pâtisserie sur mesure pour vos évenements : baptêmes, anniversaires, mariages, communions, fêtes religieuses" %>


<div class="container container-blogposts">
  <div class="text-center">
    <h2>Les actualités de Chez Valou</h2>
  </div>
  <% @blogposts.each do |blogpost| %>
    <div class="card-blogpost mt-5">
      <div class="mb-4 text-center text-lg-left">
        <h3><%= blogpost.title %></h3>
      </div>
      <div class="row h-100">
        <div class="col-xs-12 col-sm-6 my-auto">
          <%= link_to blogpost_path(blogpost) do %>
            <%= cl_image_tag blogpost.photo, quality: :auto, fetch_format: :auto, class: "blogpost-photo-small" %>
          <% end %>
        </div>
        <div class="col-xs-12 col-sm-6 h-100">
          <div class="mt-4 text-justify">
            <%= blogpost.content.truncate(600, separator: ' ').html_safe %>
            <p><em>Publié le <%= blogpost.created_at.strftime("%d/%m/%Y") %></em></p>
          </div>
          <br>
          <%= link_to "Lire la suite", blogpost_path(blogpost), class: "btn btn-ghost btn-ghost-black" %>
        </div>
      </div>
    </div>
  <% end %>
  <br><br> <br>
</div>

app/views/blogposts/show.html.erb
<% content_for :meta_title, "Chez Valou - #{@blogpost.title}" %>
<% content_for :meta_description, @blogpost.content.truncate(120) %>

<div class="container container-blogposts">
  <div class="text-center">
    <h2><%= @blogpost.title %></h2>
  </div>
  <div class="row mt-3">
    <div class="col text-center">
      <%= cl_image_tag @blogpost.photo, quality: :auto, fetch_format: :auto, class:"blogpost-photo" %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col text-justify">
      <p><%= @blogpost.content.html_safe %></p>
      <p><em>Publié le <%= @blogpost.created_at.strftime("%d/%m/%Y") %></em></p>
      <%= link_to "Retour à toutes les actualités", blogposts_path, class: "btn btn-ghost btn-ghost-black m-3" %>
    </div>
  </div>
  <br><br>
</div>

app/views/layouts/_meta_tags.html.erb
<meta charset="UTF-8">
<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">
<meta name="keywords" content="<%= meta_keywords %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/meta_tags" %>

    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="main-container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<% content_for :meta_title, "Chez Valou Pâtisserie" %>
<% content_for :meta_description, "Chez Valou Pâtisserie - Création de pâtisseries sur-mesure, à votre goût - Livraison à domicile dans la région de Bordeaux" %>

<div class="banner">
  <div class="container-fluid d-flex h-100">
    <div class="row justify-content-center align-self-center row-banner">
      <div class="col-xs-12 col-md-8 text-center">
      </div>
      <div class="col-xs-12 col-md-4 text-center mr-0 pr-1 d-none d-md-block">
        <div class="image-banner mb-2">
          <%= image_tag "logo.png" %>
        </div>
        <h1>Création de pâtisseries à votre goût</h1>
        <a class="btn btn-ghost mt-4" href="#contact">Me contacter</a>
      </div>
      <div class="col-xs-12 col-md-6 text-center pr-0 pl-0 d-block d-md-none">
        <div class="col-banner">
          <div class="image-banner mb-2">
            <%= image_tag "logo.png" %>
          </div>
          <h1>Création de pâtisseries à votre goût</h1>
          <a class="btn btn-ghost mt-4" href="#contact">Me contacter</a>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container-fluid container-red title-white">
  <div class="row">
    <div class="col">
      <div class="text-center">
        <h2>ACTUALITÉS</h2>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <% @blogposts.each do |post| %>
      <div class="col-xs-12 col-md-4 text-center">
        <div class="card-title">
          <h3><%= post.title %></h3>
        </div>
        <div class="card">
          <%= link_to blogpost_path(post) do  %>
            <%= image_tag("#{post.photo}", alt: "#{post.title}", class: "card-img-top")%>
            <div class="card-body text-left">
              <p class="card-text"><%= post.content.truncate(150) %></p>
              <div class="card-link">
                <em> En savoir plus</em>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

<div class="anchor" id="concept"></div>
<div class="container-fluid container-concept" id="#concept">
  <div class="row">
    <div class="col">
      <div class="text-center">
        <h2>CONCEPT</h2>
      </div>
    </div>
  </div>
  <div class="container mb-3">
    <div class="row">
      <div class="col text-center">
        <h3>Pour qui ?</h3>
      </div>
    </div>
    <div class="row">
      <div class="col list-for-who d-flex h-100r">
        <%= image_tag("home.png", alt: "home", class: "icon-for-who")%>
        <p class="justify-content-center align-self-cente">
          Gourmands <strong> <span class="red-word">à domicile</span></strong> : anniversaires, fêtes de famille, naissances, fêtes religieuses, dîners entre amis, ... </p>
      </div>
    </div>
    <div class="row">
      <div class="col list-for-who d-flex h-100r">
        <%= image_tag("work.png", alt: "work", class: "icon-for-who")%>
        <p class="justify-content-center align-self-cente">
          Gourmands <strong> <span class="red-word">au travail</span></strong> : comités d'entreprises, pots de départs, arbres de noël, ... </p>
      </div>
    </div>
    <div class="row">
      <div class="col list-for-who d-flex h-100r">
        <%= image_tag("asso.png", alt: "asso", class: "icon-for-who")%>
        <p class="justify-content-center align-self-cente">
          Gourmands <strong> <span class="red-word">associatifs</span></strong> : fêtes et évenements annuels, ... </p>
      </div>
    </div>
  </div>
  <br>

  <div class="lign"></div>

  <div class="container">
    <div class="row">
      <div class="col text-center mb-3 mt-3">
        <h3>Vos idées, nos créations !</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6 text-center numbers-div">
        <div class="number-step">
          1
        </div>
        <div class="text-step">
          <p>Vous me faites part de vos idées, et nous créons ensemble <strong> <span class="red-word">cette pâtisserie qui vous ressemble</span></strong></p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 text-center numbers-div">
        <div class="number-step">
          2
        </div>
        <div class="text-step">
          <p>Je passe en cuisine et prépare votre pâtisserie <strong> <span class="red-word">100% artisanal</span></strong> avec des produits locaux et de saison</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 text-center numbers-div">
        <div class="number-step">
          3
        </div>
        <div class="text-step">
          <p>Je vous livre <strong> <span class="red-word">à vélo </span></strong>(ou en voiture pour les événements hors zone, sur demande)</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 text-center numbers-div">
        <div class="number-step">
          4
        </div>
        <div class="text-step">
          <p>Vous partagez un<strong> <span class="red-word">moment gourmand </span></strong>avec vos proches, collègues, convives,...</p>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="anchor" id="about"></div>
<div class="container-fluid container-brown title-red">
  <div class="row">
    <div class="col">
      <div class="text-center">
        <h2>À PROPOS</h2>
      </div>
    </div>
  </div>

  <div class="row d-flex h-100 row-about">
    <div class="col-xs-12 col-lg-6 text-center justify-content-center align-self-center img-about-lg">
      <%= image_tag("valerie.png", alt: "Valerie Teper", class: "img-about")%>
    </div>
    <div class="col-xs-12 col-lg-6 justify-content-center align-self-center">
      <div class="text-about mx-auto">
        <p>Moi, c'est Valérie, pâtissière passionnée ! Vous ne le croirez peut-être pas, mais avant de vivre de ma passion, j'étais ingénieure dans l'industrie. Une démission et un CAP pâtisserie plus tard me voilà désormais entrepreneur... et heureuse ! C'est ce bonheur que je veux partager, et que j'aime retrouver dans les yeux des gourmands qui dégustent mes créations avec cette étincelle de plaisir qui tout simplement me fait adorer mon métier chaque jour.
          <br><br>
        Perfectionniste - être ingénieure laisse des traces indélébiles - et inlassablement à la recherche de nouvelles idées gourmandes, je créé pour vous des <strong> <span class="red-word">pâtisseries sur-mesure </span></strong>(saveur, texture, visuel, vegan, sans gluten, sans allergènes, etc) et <strong> <span class="red-word">100% artisanales </span></strong>. Vous êtes tous concernés ! Ētes vous prêts à partager un moment gourmand ?</p>
      </div>
    </div>
  </div>
  <br><br>
</div>


<div class="anchor" id="shipping"></div>
<div class="container-fluid title-brown">
  <div class="row">
    <div class="col">
      <div class="text-center">
        <h2>LIVRAISON</h2>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col text-center">
      <p>Envie d'une pâtisserie sur-mesure ? Grâce à cette carte découvrez si <strong> <span class="red-word">Chez Valou Pâtisserie </span></strong>vient jusqu'à chez vous ! <br>Des questions ? Vous êtes hors-zone ? N'hésitez pas à me contacter !</p>
    </div>
  </div>
  <br>
  <div class="row mb-4">
    <iframe src="https://www.google.com/maps/d/embed?mid=1SR3gIYQMqjlE81hHnLt4T6EvzuxuKG4e" width="100%" height="480"></iframe>
  </div>
</div>

<div class="anchor" id="contact"></div>
<div class="container-fluid container-hazelnut title-white">
  <div class="row">
    <div class="col">
      <div class="text-center">
        <h2>CONTACT</h2>
      </div>
    </div>
  </div>
  <p class="text-white text-center">N'hésitez pas à me contacter pour commencer à échanger sur cette pâtisserie qui vous ressemble, ou pour plus d'informations pour une livraison hors zone par exemple. <br> Dans tous les cas, pensez à me préciser la date et le lieu de l'événement. </p>
  <form action="https://formspree.io/contact.chezvalou@gmail.com" accept-charset="utf-8" method="POST" />
    <div class="form-row">
      <div class="col">
        <div class="form-row">
          <div class="col">
            <input type="text" name="first-name" class="form-control" placeholder="Prénom" required="">
          </div>
          <div class="col">
            <input type="text" name="last-name" class="form-control" placeholder="Nom" required="">
          </div>
        </div>
        <div class="form-row mt-2">
          <div class="col">
            <input type="text" class="form-control" name="_replyto" id="email-address" placeholder="Email" required="">
          </div>
        </div>
        <div class="form-row mt-2">
          <div class="col">
            <input type="text" class="form-control" name="telephone" id="telephone" placeholder="Téléphone">
          </div>
        </div>
      </div>
      <div class="col">
        <textarea name="complaint" rows="7" id="complaint" class="form-control" placeholder="Message" required=""></textarea>
      </div>
    </div>
    <input type="hidden" name="_subject" id="email-subject" value="Contact via site web">
  <div class="row">
    <div class="col text-center">
      <input type="submit" value="Envoyer" class="btn btn-white mt-4">
    </div>
  </div>
  <br>
</form>
</div>

<div class="container-fluid title-red">
  <div class="row">
    <div class="col">
      <div class="text-center">
        <h2>INSTAGRAM</h2>
      </div>
    </div>
  </div>
  <!-- SnapWidget -->
  <!-- SnapWidget -->
  <script src="https://snapwidget.com/js/snapwidget.js"></script>
  <iframe src="https://snapwidget.com/embed/800503" class="snapwidget-widget" allowtransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden;  width:100%; "></iframe>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-item footer-copyright text-center justify-content-center align-self-center">
    <p>
    <%= link_to "Mentions Légales", mentions_legales_path, class: "link-legals" %>
    </p>
  </div>
  <div class="footer-item footer-infos text-center justify-content-center align-self-center">
    <p>Chez Valou Pâtisserie</p>
    <a href="mailto:contact.chezvalou@gmail.com"><p>contact.chezvalou@gmail.com</p></a>
    <a href="tel:+33618661933"><p>06 18 66 19 33</p></a>
  </div>
  <div class="footer-item footer-links text-center justify-content-center align-self-center">
    <a href="https://www.facebook.com/chezvaloupatisserie" target="_blank"><%= image_tag("facebook.png", alt: "facebook", class: "image-social")%></a>
    <a href="https://www.instagram.com/chez_valou_patisserie/" target="_blank"><%= image_tag("instagram.png", alt: "instagram", class: "image-social")%></a>
  </div>
  <div class="footer-item design-webdev">
    <p>© Copyright Chez Valou Pâtisserie | Design : <a href="http://www.alixdesalins.com/" target="_blank">alix ds</a> | Développement web : <a href="https://www.claire-gautier.com" target="_blank">Claire Gautier</a></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <div class="navbar-container-image d-flex h-100">
    <%= link_to root_path, class: "navbar-brand justify-content-center align-self-center mr-5 mb-1" do %>
      <%= image_tag "logo.png" %>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-bars"></i>
  </button>

  <div class="collapse navbar-collapse flex-grow-1" id="navbarSupportedContent">
    <ul class="navbar-nav text-center text-lg-right mr-auto d-flex justify-content-between w-100">
      <li>
        <%= link_to "ACTUALITÉS", blogposts_path, class: "nav-item" %>
      </li>
      <li>
        <%= link_to "CONCEPT", root_path(anchor: "concept"), class: "nav-item" %>
      </li>
      <li>
        <%= link_to "À PROPOS", root_path(anchor: "about"), class: "nav-item" %>
      </li>
      <li>
        <%= link_to "LIVRAISON", root_path(anchor: "shipping"), class: "nav-item" %>
      </li>
      <li>
        <%= link_to "CONTACT", root_path(anchor: "contact"), class: "nav-item" %>
      </li>
    </ul>
  </div>
</div>